### ISSUE TITLE
ServiceCapteur pb d'insertion données

### ISSUE THREAD

**Issue by mxyns** [Lgt2x/P2I-P4#4]
les données sont envoyées par l'arduino au format "idStation:idTypeCapteur:valeur" et pas "idStation:idCapteur:valeur"

il y a un pb au niveau de l'insertion je pense, p-ê que les mesures sont ajoutées en considérant idTypeCapteur comme idCapteur ce qui fait qu'on a pas de mesures pour les capteurs d'id > max(idTypeCapteur) = 9 et que les mesures ne sont pas associées au bon capteur.

=> ça fait crash l'interface du coup vu qu'elle reçoit 4 grandeurs physiques et 2 ou 3 valeurs vu que les mesures sont associées au mauvais capteur. 

si c'est pas ça le pb vient d'interface et faut que je recheck mes requêtes sql

**Comment by Lgt2x** [comment]
Fixé dans le commit b9dda64b5cd4f77f9732444b6007665589d40614
