### ISSUE TITLE
affichage points graphique dégueu

### ISSUE THREAD

**Issue by mxyns** [Lgt2x/P2I-P4#6]
il y a un problème avec le graphique, surement avec la manière de relier les points puisque les droites horizontales et diagonales sont affichées correctement

**Comment by Lgt2x** [comment]
Vous en pensez quoi d'avoir juste un nuage de points et de ne rien tracer ? Sinon c'est illisible

**Comment by mxyns** [comment]
fixé dans le commit e15a5db877e718555d6a6631069f4f59832767aa
